repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
    -   id: trailing-whitespace
    -   id: end-of-file-fixer
    -   id: check-yaml
    -   id: check-added-large-files

-   repo: https://github.com/gitleaks/gitleaks
    rev: v8.16.3
    hooks:
    -   id: gitleaks

-   repo: local
    hooks:
    -   id: detect-api-keys
        name: Detect API Keys
        entry: bash -c 'for file in "$@"; do if [[ "$file" != *".env"* ]]; then if grep -q "hf_" "$file" || grep -q "AIza" "$file"; then echo "Potential API key found in $file"; exit 1; fi; fi; done'
        language: system
        files: ''
        exclude: '\.env.*$'
